docs: ssg
ice-lab/site pull request #33
Opened 2021-09-03 04:09 UTC by luhc228

2021-09-06 04:00 UTC, ClarkXia commented
prerender 文档顺手删了吧

2021-09-06 06:45 UTC, imsobear commented on docs/guide/advanced/ssr.md
> -  - publicPath: 选填，静态资源的公共路径，默认为 `/`
是不是应该留着，然后标识 2.0 版本不需要传递？

2021-09-06 06:53 UTC, imsobear requested changes

2021-09-06 06:53 UTC, imsobear commented on docs/guide/advanced/ssg.md
> +### 使用 Nginx
GitHub Pages 之类的跟这个也是一样

2021-09-06 06:53 UTC, imsobear commented on docs/guide/advanced/ssg.md
> +对于有部分页面组件开启 SSR 的情况，生产环境下需要对应的服务端进行渲染，核心逻辑如下：
这个是什么场景？感觉并不是很常见？

2021-09-06 06:53 UTC, imsobear commented on docs/guide/advanced/ssg.md
> +    }
这里不要讲 getInitialProps 了吧

2021-09-06 06:53 UTC, imsobear commented on docs/guide/advanced/ssg.md
> +预渲染默认不渲染动态路由里的所有页面，如果需要渲染动态路由中的页面，可以在`src/routes.ts` 中配置 `getStaticPath` 函数：
这里动态路由建议给个示例：不渲染动态路由（比如 `/project/:id`），下面的 static 跟这个保持一致。

2021-09-07 08:45 UTC, luhc228 commented on docs/guide/advanced/ssg.md
> +对于有部分页面组件开启 SSR 的情况，生产环境下需要对应的服务端进行渲染，核心逻辑如下：
之前问过 shuilan，无线端场景会有这种 SSG 和 SSR 同时使用的场景，文档还是先留着吧

2021-09-07 08:56 UTC, luhc228 commented
> prerender 文档顺手删了吧

done

2021-09-07 08:56 UTC, luhc228 commented on docs/guide/advanced/ssg.md
> +预渲染默认不渲染动态路由里的所有页面，如果需要渲染动态路由中的页面，可以在`src/routes.ts` 中配置 `getStaticPath` 函数：
已增加

2021-09-07 08:56 UTC, luhc228 commented on docs/guide/advanced/ssg.md
> +    }
已去掉

2021-09-07 08:59 UTC, ClarkXia approved these changes

2021-09-07 09:03 UTC, luhc228 commented on docs/guide/advanced/ssg.md
> +### 使用 Nginx
标题我改为使用静态资源服务器，可能好点

2021-09-07 09:17 UTC, luhc228 commented on docs/guide/advanced/ssr.md
> -  - publicPath: 选填，静态资源的公共路径，默认为 `/`
不用留了，目前用的人比较少，直接去掉吧

2021-09-07 12:54 UTC, merged